apiVersion: v1
kind: Pod
metadata:
  name: nginx 
  labels:
    app: nginx
    tier: frontend
spec:
  containers:
    - name: my-container
      image: nginx
      ports:
        - containerPort: 80

---